### ISSUE TITLE
The Road Map

### ISSUE THREAD

**Issue by znck** [znck/vue-language-support#1]
## Intellisense Features

- [x]  Completion for component tags (Local and Global)
- [ ]  Completion for component props
- [ ]  Completion for component attributes (inner element)
- [ ]  Completion for event name and modifiers
- [ ]  Completion for slot name and scope arguments
- [ ]  GoTo definition of component/prop/slot/emit
- [ ]  Hover component tag to see component information
- [ ]  Hover component prop to see prop information

## Refactor Features

- [ ]  Rename global component
- [ ]  Rename API (data, computed, methods, props, slots, events)
- [ ]  Extract statement[s] to method
- [ ]  Extract expression to computed property
- [ ]  Extract template to component

---------------------------------------------------------------------------
Feature requests are welcome!
